### ISSUE TITLE
Fix the .dot components

### ISSUE THREAD

**Issue by brettlangdon** [underdogio/pup#72]
This is likely a mix of issues with `.inline-center` and `.dot`, we can't quite get them to line up with text exactly like we want :(

**Comment by restlessbit** [comment]
Instead of vertically aligning with flexbox, you could try aligning them by setting `display: inline-block` and `vertical-align: middle` for both elements

**Comment by brettlangdon** [comment]
Hmm... seems to work, but I think `vertical-align: baseline` lines up a little better.

## Baseline
![image](https://cloud.githubusercontent.com/assets/1320353/21052799/ba33877c-bdf4-11e6-974f-6ab3e60ba4d0.png)


## Middle
![image](https://cloud.githubusercontent.com/assets/1320353/21052821/d7404238-bdf4-11e6-979a-c990d1762f6a.png)


However, is this starting to get very specific to `.dot`?

Should we consider:

```html
<span class="dot">
  <span class="dot__label">Blue:&nbsp;</span>
  <span class="dot__icon"></span>
</span>
```

Or just a more... robust `.dot` component?

**Comment by brettlangdon** [comment]
Also, `baseline` really only works for `.dot--small` just a normal dot kind of sucks and doesn't line up right... maybe we should drop `.dot--small` and make that the default/only size?

**Comment by brettlangdon** [comment]
@restlessbit what do you think about separating `.inline-center` and `.dot`. It doesn't seem like I can get exactly what I want... unless we add an `.inline-baseline` helper as well... which seems weird.

Does it make sense to have a component structure like I suggested with having the label be a part of `.dot`?

**Comment by restlessbit** [comment]
Having a block of text with `inline-center` and applying that to the block looks good to me:

<img width="399" alt="screen shot 2016-12-12 at 1 08 07 pm" src="https://cloud.githubusercontent.com/assets/6979137/21110677/223489ec-c06c-11e6-8f98-e7f43927c58b.png">

<img width="555" alt="screen shot 2016-12-12 at 1 08 11 pm" src="https://cloud.githubusercontent.com/assets/6979137/21110681/25b8391a-c06c-11e6-9334-87da5e139b5f.png">

**Comment by brettlangdon** [comment]
idk, the dot looks too high to me.

Looking at it in this context:

#### Baseline
![image](https://cloud.githubusercontent.com/assets/1320353/21110792/aa0abe22-c06c-11e6-9e9f-9d9bdb8401fb.png)

#### Middle
![image](https://cloud.githubusercontent.com/assets/1320353/21110802/b14a2c68-c06c-11e6-8d79-dd82f8cb8696.png)


Middle just... looks off to me

**Comment by restlessbit** [comment]
i think both are fine tbh 😺
